name: Hello World Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
      - name: Say Goodbye
        run: echo "Goodbye, World!
      - name: Say Welcome
        run: echo "Welcome to the GitHub Actions!"
      - name: Show env info
        run: |
          echo "Running on: ${{ runner.os }}"
          echo "GitHub Workspace: ${{ github.workspace }}"
